name: Memory Versioning

on:
  push:
    branches: [main]
    paths:
      - 'memory/**'

jobs:
  version-track:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Track memory changes
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "MEMORY_VERSION=$TIMESTAMP-${GITHUB_SHA::7}" >> $GITHUB_ENV
          
          mkdir -p memory/versions/${GITHUB_ENV_MEMORY_VERSION}
          cp -r memory/* memory/versions/${GITHUB_ENV_MEMORY_VERSION}/
          
          git config --global user.name "SSES Memory Versioning"
          git config --global user.email "smes-bot@example.com"
          git add memory/versions
          git commit -m "Versioning snapshot ${GITHUB_ENV_MEMORY_VERSION}"
          git push origin main

      - name: Update CHANGELOG
        run: |
          echo "\n## ${GITHUB_ENV_MEMORY_VERSION} - $(date +%Y-%m-%d)" >> memory/CHANGELOG.md
          git diff --name-only HEAD^ HEAD -- memory/ | grep -v versions/ >> memory/CHANGELOG.md
          git add memory/CHANGELOG.md
          git commit -m "Update changelog for ${GITHUB_ENV_MEMORY_VERSION}"
