name: SSES Memory Versioning

on:
  push:
    branches: [ main, sses-implementation ]
    paths:
      - 'src/smolagents/sses/memory/**'

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history for proper changelogs
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
        
    - name: Process memory changes
      run: |
        python src/smolagents/sses/tools/memory_processor.py
        
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Memory Update [automated]"
        file_pattern: src/smolagents/sses/memory/**
        commit_user_name: "Memory Processor"
        commit_user_email: "memory-processor@smolagents-sses.dev"
        commit_author: "Memory Processor <memory-processor@smolagents-sses.dev>"
